export const data = [
  {
     id: 0,
     question: "Kedy ste naposledy jedli?",
     respFyzio: "pred viac ako 3 hodinami",
     adviceFyzio: "super, Váš hlad je fyziologický, najedzte sa",
     respEmot: "pred hodinou",
     adviceEmot: [
       "ak ste pred hodinou jedli niečo malé, teraz je čas na kvalitné hlavné jedlo (250/300g)",
       "ak ste pred hodinou obedovali alebo večerali, tento Váš hlad je emočný, skúste:",
       "dôkladne si umyť zuby",
       "pripraviť si šálku kávy (po obede) alebo čaju (po večeri)",
       "dopriať si sprchu alebo horúci kúpeľ",
       "poliať kvety alebo urobiť niečo malé v záhrade",
       "odísť z miestnosti, kde je jedlo a sústrediť sa na niečo, čo Vás baví",
       "odísť z bytu alebo pracoviska bez peňazí a kreditnej karty aspoň na 30 min",
     ],
   },
   {
     id: 1,
     question: "Nakoľko je Váš hlad intenzívny?",
     respFyzio: "cítim hlad, ale v pohode sa sústredím na to, čo práve robím",
     respEmot: "náhle ma prepadol taký hlad, že sa nedokážem sústrediť na nič iné, len na jedlo",
     adviceFyzio: "super, Váš hlad je fyziologický, najedzte sa",
     adviceEmot: [
       "zhlboka sa nadýchnuť, zavrieť oči a zhlboka dýchať niekoľko minút, pri nádychu si opakujte „Zvládnem to“,  pri výdychu „Zbavujem sa svojho hnevu, strachu, napätia, hanby, smútku, nudy...“",
       "ísť k umývadlu a pustiť si na ruky prúd teplej vody aspoň na 3 minúty",
       "dať si na čelo / na zátylok studený obklad a zhlboka dýchať aspoň 3 minúty",
       "vystaviť svoju tvár na 10 minút slnku alebo intenzívnemu svetlu lampy",
       "zapáliť si sviečku alebo si dopriať extra dávku obľúbeného parfumu",
       "pustiť si obľúbenú relaxačnú hudbu",
       "zavolať alebo napísať niekomu, kto Vás podporí",
       "uchýliť sa k modlitbe, afirmáciám alebo k meditácii",
     ],
   },
   {
     id: 2,
     question: "Na čo máte chuť?",
     respFyzio: "na nič konkrétne, chcem sa len dobre najesť",
     respEmot: "mám chuť len na jedno jediné jedlo, nič iné mi neprinesie uspokojenie",
     adviceFyzio: "super, Váš hlad je fyziologický, najedzte sa",
     adviceEmot: [
       "vypiť veľký pohár čistej vody",
       "užiť magnézium (300-400mg denne)",
       "užiť vitamín B6 (100mg denne)",
       "pripraviť si zázvorový čaj",
       "vypiť pohár studeného (acidofilného) mlieka alebo teplého kakaa",
       "dať si do úst 3 ks žuvačky bez cukru a poctivo žuť minimálne 15 minút",
     ],
   },
   {
     id: 3,
     question: "Ako sa cítite, keď jete?",
     respFyzio: "proste sa najem, pochutnám si a idem ďalej",
     respEmot: "mám pocit viny, zlyhania, hanby",
     adviceFyzio: "super, Váš hlad je fyziologický, najedzte sa",
     adviceEmot: [
       "naložiť si jedlo vždy úhľadne na tanier alebo do misky",
       "jesť vždy sediac za stolom, mimo dosahu televízie",
       "sústrediť sa iba na jedlo ( odložiť tablet, mobil, knihu...)",
       "po jedle si vždy dôkladne umyť zuby a upratať stôl, na ktorom ste jedli",
       "-	medzi jedlami nemať jedlo (najmä drobné pochutiny) vo svojej blízkosti",
     ],
   },
 ];
 